version: '{build}'

environment:
  matrix:
  # Comilers matrix
  # - env_cmake_generator: "Visual Studio 11 2012"
  #   env_cmake_configuration: Debug
  #   env_fbxsdk_path: "http://download.autodesk.com/us/fbx/2017/2017.1/fbx20171_fbxsdk_vs2012_win.exe"
  # - env_cmake_generator: "Visual Studio 12 2013"
  #   env_cmake_configuration: Debug
  #   env_fbxsdk_path: "http://download.autodesk.com/us/fbx/2017/2017.1/fbx20171_fbxsdk_vs2013_win.exe"
  # - env_cmake_generator: "Visual Studio 14 2015"
  #   env_cmake_configuration: Debug
  #   env_fbxsdk_path: "http://download.autodesk.com/us/fbx/2017/2017.1/fbx20171_fbxsdk_vs2015_win.exe"
  # - env_cmake_generator: "Visual Studio 14 2015"
  #   env_cmake_configuration: Release
  #   env_fbxsdk_path: "http://download.autodesk.com/us/fbx/2017/2017.1/fbx20171_fbxsdk_vs2015_win.exe"
  # - env_cmake_generator: "Visual Studio 14 2015 Win64"
  #   env_cmake_configuration: Debug
  #   env_fbxsdk_path: "http://download.autodesk.com/us/fbx/2017/2017.1/fbx20171_fbxsdk_vs2015_win.exe"
  # - env_cmake_generator: "Visual Studio 14 2015 Win64"
  #   env_cmake_configuration: Release
  #   env_fbxsdk_path: "http://download.autodesk.com/us/fbx/2017/2017.1/fbx20171_fbxsdk_vs2015_win.exe"
  # # No fbx sdk
  # - env_cmake_generator: "Visual Studio 14 2015"
  #   env_cmake_configuration: Release
  # Emscriten
  - env_cmake_generator: "Visual Studio 14 2015"
    env_cmake_configuration: Release
    env_emscripten: 1

install:
# Setup Fbx sdk
- ps: >-
    if ($Env:env_fbxsdk_path) {
      md fbx
      cd fbx
      Start-FileDownload $Env:env_fbxsdk_path "fbxsdk.exe"
      Start-Process -FilePath "fbxsdk.exe" /S -Wait
      cd ..
    }
- ps: >-
    if ($Env:env_emscripten) {
      md emscriten
      cd emscriten
      Start-FileDownload "https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.zip"
      7z x emsdk-portable.zip
      dir
      ./emsdk update
      ./emsdk install latest
      . ./emsdk activate latest
      . ./emsdk_env.bat
      cd ..
      $Env:env_cmake_toolchain="-DCMAKE_TOOLCHAIN_FILE=C:\projects\ozz-animation\emscriten\emscripten\1.37.9/cmake/Modules/Platform/Emscripten.cmake"
    }

build_script:
- mkdir build
- cd build
- echo %EMSCRIPTEN%
- echo %env_cmake_toolchain%
- cmake  -G "%env_cmake_generator%" %env_cmake_toolchain% -Dozz_build_tests=1 -DCMAKE_BUILD_TYPE=%env_cmake_configuration% ..
- cmake --build ./ --config %env_cmake_configuration%

test_script:
- ctest --build-config %env_cmake_configuration%
